### ISSUE TITLE
مسخره پدرتیم ما؟

### ISSUE THREAD

**Issue by appt2** [CaiMuCheng/Leaf-IDE#1]
جای این که بک برنامه غیرواقعی تولید کنی که کار نکنه بیا روی برنامه من کار کن 
https://github.com/appt2/Ghost-web-ide
تنبل نباش 
@CaiMuCheng

**Comment by CaiMuCheng** [comment]
又不是给你用的，你急什么？爱用不用，如果觉得吵火速 unfollow me

谢谢你的 Joker Project，因为这又有什么重点呢？
